title: My Awesome Site
email: your-email@example.com
description: >- 
  This is my awesome site built with Jekyll.
baseurl: "https://dukem-csgo.github.io" 
url: "/DuKeM-CSGO" 

theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag