title: My Awesome Site
email: your-email@example.com
description: >- 
  This is my awesome site built with Jekyll.
url: "https://dukem-csgo.github.io" 
baseurl: "/DuKeM-CSGO" 

#theme: jekyll-theme-midnight

kramdown:
  input: GFM

seo:
  json_ld: false
  meta: false
  images: false